object Versions {

    const val supportLibraryVersion = "27.1.1"
    const val retrofitVersion = "2.5.0"
    const val converterGsonVersion = "2.1.0"
    const val retrofitConvertersVersion = "2.1.0"
    const val gsonVersion = "2.6.1"
    const val picassoVersion = "2.5.2"
    const val circleImageVersion = "2.2.0"
    const val butterKnifeVersion = "10.2.3"
    const val calligraphyVersion = "2.3.0"
    const val sneakerVersion = "1.0.1"
    const val daggerVersion = "2.15"
    const val firebaseVersion = "16.0.1"
    const val firebaseCoreVersion = "16.0.0"
    const val fireStoreVersion = "17.0.1"
    const val transitionEveryWhereVersion = "1.7.6"
    const val rxJavaVersion = "2.3"
    const val okhttpVersion = "3.9.1"
    const val mockitoVersion = "2.7.22"
    const val chipCloudVersion = "3.0.5"
    const val flexboxVersion = "0.3.2"
    const val timeAgoVersion = "3.0.2"
    const val playServicesVersion = "16.0.0"
    const val googleMapsVersion = "15.0.1"
    const val fuelHTTPversion = "1.15.1"
}